### ISSUE TITLE
Running Sample Project

### ISSUE THREAD

**Issue by smatthews1999** [VelcroPhysics/VelcroPhysics#1]
Hello,

I am able to run the "HelloWorld" project (in Samples)without incident, but when I try to run "Samples" project (in Samples) I get two errors.  Not sure what this are as I am not familiar with XNA or Monogame.

`Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"C:\Users\smatt\code\VelcroPhysics\Samples\Samples\Content\Content.mgcb" /platform:Windows /outputDir:"C:\Users\smatt\code\VelcroPhysics\Samples\Samples\Content\bin\Windows" /intermediateDir:"C:\Users\smatt\code\VelcroPhysics\Samples\Samples\Content\obj\Windows" /quiet" exited with code 1.	Samples (Samples\Samples)			

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to create processor 'TextureToVerticesProcessor'	Samples (Samples\Samples)	C:/Users/smatt/code/VelcroPhysics/Samples/Samples/Content/Pipeline/Object.png		

`

**Comment by smatthews1999** [comment]
I was able to run the samples by commenting out all references to loading Object.png (which looked like a logo).  The issue seems to the 'TextureToVerticesProcessor' not working referred to in the 'content.mgcb' file.

**Comment by Genbox** [comment]
Right. This happens because MonoGame is referencing a DLL in the content.mgcb file that does not exist before you have compiled the content pipeline projects. It is "solved" by compiling the project again after it failed the first time. I will setup build dependencies such that the DLL is compiled before the samples.
