### ISSUE TITLE
BayazitDecomposer is protected.

### ISSUE THREAD

**Issue by smatthews1999** [VelcroPhysics/VelcroPhysics#24]
In the Farseer [documentation](http://farseerphysics.codeplex.com/documentation), it mentions making use of the BayazitDecomposer to create polygons.  However in Velcro this class is protected and not available.  Can/should this (and other decomposers) be made public?

**Comment by Genbox** [comment]
I changed that to use the Triangulate class instead. It checks the input and output of each algorithm depending on the values in Settings.cs. The documentation is not up to date on many points.

**Comment by smatthews1999** [comment]
Ok great.  I did use the BayazitDecomposer by making it public... but I will try that.
