### ISSUE TITLE
Truly polygon Vertices 

### ISSUE THREAD

**Issue by yami0625** [VelcroPhysics/VelcroPhysics#25]
I using a BodyFactory.CreatePolygon() and spawn polygons.
But, some vertices are removed by GiftWrap.GetConvexHull().
So, now I add polygon...
![2017_04_29 0_05_01](https://cloud.githubusercontent.com/assets/6112926/25534874/3731aab2-2c70-11e7-96a0-2f36d63979e4.png)
I want to change like this.
![2017_04_29 0_04_39](https://cloud.githubusercontent.com/assets/6112926/25534894/4513f7c0-2c70-11e7-98b8-c64b33b44d21.png)

**Comment by Genbox** [comment]
The engine does not support concave polygons. You could try to use chain shape instead for your terrain, or split your terrain into smaller rectangles that are convex.

If everything you create is predefined convex, you can turn off the Giftwrap convex hull by setting `Settings.UseConvexHullPolygons = false`

**Comment by yami0625** [comment]
I split vertices using point and nearby point. As a result, I solved this problem.
thanks :)
