### ISSUE TITLE
BeginContact event issue

### ISSUE THREAD

**Issue by yami0625** [VelcroPhysics/VelcroPhysics#28]
I added BeginContact event to world.
`world.ContactManager.BeginContact += new BeginContactDelegate(OnBeginContact);`
And, return false on "OnBeginContact" method.
On FarseerPhysics, I could disabled bodies contact to use this way.
But now, I can't disable bodies contact at VelcroPhysics.
How should I do this?

**Comment by Genbox** [comment]
This project is currently under development and everything is subject to change. If you need a stable physics engine, please [download Farseer Physics Engine](http://farseerphysics.codeplex.com/).
