### ISSUE TITLE
"raints"

### ISSUE THREAD

**Issue by HughPH** [VelcroPhysics/VelcroPhysics#39]
You did the same thing as me. Search & replace "const" => ""
Result:
// Integrate velocities, solve velocity raints, and integrate positions.

I thought "raints" was trendy-speak for "constraints" - until I realised what I'd done. Made me laugh when I saw the same thing in someone else's code!

Might be worth just having a quick scan through the code to make sure all constraints are still correctly named ;)

**Comment by Genbox** [comment]
Damn, I thought I found them all. This one is 7 years old. Will keep this issue open until I've squashed them all.
