### ISSUE TITLE
Requires XNA, no mention of that on the description or front page

### ISSUE THREAD

**Issue by nfoste82** [VelcroPhysics/VelcroPhysics#51]
If the engine requires XNA, which hasn't been supported for years, then that should probably be mentioned on the front page for the project.

**Comment by Genbox** [comment]
I does not require XNA. It has zero-copy integration with MonoGame, but you can run VelcroPhysics without any dependencies at all since it has its own Vector2 etc. classes. Will update the front page with this information.
