### ISSUE TITLE
Possible license breach?

### ISSUE THREAD

**Issue by Rikarin** [VelcroPhysics/VelcroPhysics#71]
I've seen your statement "This is a sponsored project. That means in order to create issues and pull requests, or use the project commercially, you must become a sponsor."

You used the Box2D code and reimplemented it in C# which forces your project to use the same license as Box2D is using, so it prohibits you to restrict using this library for commercial use without sponsoring your project.

**Comment by Genbox** [comment]
That is not how it works. [Box2D is licensed under MIT](https://github.com/erincatto/box2d/blob/main/LICENSE), which allows sublicensing, thereby allowing further restrictions to the software. This project is published under MIT as well but with the added restrictions described in the readme.
